<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RiseAndShop" nsURI="http:///RiseAndShop.ecore" nsPrefix="RiseAndShop">
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currEmployee" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseUtils">
    <eOperations name="addEmployee" ordered="false" lowerBound="1"/>
    <eOperations name="UpdateEmployee" ordered="false" lowerBound="1"/>
    <eOperations name="deleteEmployee" ordered="false" lowerBound="1"/>
    <eOperations name="addProduct" ordered="false" lowerBound="1"/>
    <eOperations name="deleteProduct" ordered="false" lowerBound="1"/>
    <eOperations name="addStore" ordered="false" lowerBound="1"/>
    <eOperations name="updateStore" ordered="false" lowerBound="1"/>
    <eOperations name="deleteStore" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Store">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" ordered="false"
        upperBound="-1" eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fullInventory" ordered="false"
        lowerBound="1" eType="#//Inventory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" ordered="false"
        upperBound="-1" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inventory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" ordered="false"
        upperBound="-1" eType="#//Categories"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Categories">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" ordered="false"
        lowerBound="1" eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplierInfo" ordered="false"
        lowerBound="1" eType="#//Supplier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supplier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contactInfo" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Notification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notificationId" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cartId" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerId" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" ordered="false"
        upperBound="-1" eType="#//CartItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paymentIssued" ordered="false"
        lowerBound="1" eType="#//Payment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="review" ordered="false"
        lowerBound="1" eType="#//Review"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Review">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Salary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chequeId" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../org.eclipse.uml2.types/model/Types.ecore#//Real"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Utils">
    <eOperations name="checkUsername" ordered="false" lowerBound="1"/>
    <eOperations name="isValidPassword" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Superviser" eSuperTypes="#//Employee">
    <eOperations name="UpdateProduct" ordered="false" lowerBound="1"/>
    <eOperations name="addNewProduct" ordered="false" lowerBound="1"/>
    <eOperations name="DeleteProduct" ordered="false" lowerBound="1"/>
    <eOperations name="getStockDetails" ordered="false" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeamLeader" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="notifications" ordered="false"
        upperBound="-1" eType="#//Notification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cashier" eSuperTypes="#//Employee">
    <eOperations name="notifyLowStock" ordered="false" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carts" ordered="false"
        upperBound="-1" eType="#//Cart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manager" eSuperTypes="#//Employee">
    <eOperations name="getProductLocation" ordered="false" lowerBound="1"/>
    <eOperations name="updateCategory" ordered="false" lowerBound="1"/>
    <eOperations name="getSalesDetails" ordered="false" lowerBound="1"/>
  </eClassifiers>
</ecore:EPackage>
